services:  
  db:
    image: postgres
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432
    env_file:
      - .env
  
  web:
    build: .
    depends_on:
      - db
    ports:
      - 8080:80
    env_file:
      - .env
    
volumes:
  database: